### ISSUE TITLE
Can't deploy on main iMac

### ISSUE THREAD

**Issue by henryom** [Team2915/RobotCode-2016#1]
We cannot deploy from the main iMac.  It says it cannot find some java library.  I think we can deploy from our laptops, including mine.  I think we just need to move a library to the GitHub folder on the iMac.

-Henry OM

**Comment by henryom** [comment]
I think I can manage on Saturday by deploying from my laptop and running from the iMac.  I can bring my hard drive too.

**Comment by andrew-h-123** [comment]
How much space do you have on the hard drive? Did you boot camp yet?

**Comment by henryom** [comment]
We fixed it, i do not want to bootcamp.  Why are you not here?

**Comment by andrew-h-123** [comment]
Because I have stuff to do...
